package NATrain.quads;

public enum GlobalQuadType {
    SIMPLE_TRACK_QUAD,
    DOUBLE_TRACK_QUAD,
    SIGNAL_QUAD,
    SWITCH_QUAD,
    BLOCKING_TRACK_QUAD,
    BLOCKING_SIGNAL_QUAD,
    ARRIVAL_SIGNAL_QUAD,
    GATE_QUAD,
    SERVO_QUAD,
    POLARITY_CHANGER_QUAD,
    BUTTON_QUAD,
    SLIDER_QUAD,
    ON_OFF_QUAD,
}
